<a href="https://colab.research.google.com/github/AishwaryaMuchandi/B.E-Project/blob/master/Basic_Alex_net.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install tensorflow==1.14.0
!pip install keras==2.2.0

     |████████████████████████████████| 109.2MB 99kB/s 
     |████████████████████████████████| 491kB 43.5MB/s 
     |████████████████████████████████| 3.2MB 38.4MB/s 
  Found existing installation: tensorflow-estimator 2.2.0rc0
    Uninstalling tensorflow-estimator-2.2.0rc0:
      Successfully uninstalled tensorflow-estimator-2.2.0rc0
  Found existing installation: tensorboard 2.2.0
    Uninstalling tensorboard-2.2.0:
      Successfully uninstalled tensorboard-2.2.0
  Found existing installation: tensorflow 2.2.0rc2
    Uninstalling tensorflow-2.2.0rc2:
      Successfully uninstalled tensorflow-2.2.0rc2
     |████████████████████████████████| 307kB 2.7MB/s 
     |████████████████████████████████| 51kB 7.1MB/s 
ERROR: tensorflow 1.14.0 has requirement keras-applications>=1.0.6, but you'll have keras-applications 1.0.2 which is incompatible.
ERROR: tensorflow 1.14.0 has requirement keras-preprocessing>=1.0.5, but you'll have keras-preprocessing 1.0.1 which is incompatible.
  Found exist

In [0]:
import tensorflow
import keras
from keras.datasets import mnist
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import  Dense,Dropout,Activation,Flatten
from keras.layers import Conv2D,MaxPooling2D,ZeroPadding2D
from keras.layers.normalization import BatchNormalization
from keras.optimizers import Adam
from keras.regularizers import l2

In [0]:
(X_train,y_train),(X_test,y_test)=mnist.load_data()

In [0]:
print("X_train",X_train.shape)
print("X_test",X_test.shape)


X_train (60000, 28, 28)
X_test (10000, 28, 28)


In [0]:
print(X_train.shape[0],'train samples')
print(X_test.shape[0],'test samples')

60000 train samples
10000 test samples


In [0]:
num_classes=10
y_train=keras.utils.to_categorical(y_train,num_classes)
Y_test=keras.utils.to_categorical(y_test,num_classes)

In [0]:
print(y_train)
print(y_test)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
[7 2 1 ... 4 5 6]


In [0]:
X_train = X_train.reshape(60000, 28, 28, 1)
X_test = X_test.reshape(10000, 28, 28, 1)

In [0]:
l2_reg=0

def create_model():
  model=Sequential()

  model.add(Conv2D(256,(11,11),input_shape=X_train.shape[1:],padding='same',strides=(1,1),kernel_regularizer=l2(l2_reg)))
  model.add(BatchNormalization(axis=-1))
  model.add(Activation('relu'))
  model.add(MaxPooling2D(pool_size=(2,2),strides=(2,2),padding='valid'))

  model.add(ZeroPadding2D(padding=(2,2),data_format="channels_last"))
  model.add(Conv2D(128,(5,5),padding='same',strides=(1,1))) 
  model.add(BatchNormalization())
  model.add(Activation('relu'))
  model.add(MaxPooling2D(pool_size=(3,3),))


  model.add(ZeroPadding2D(padding=(1,1)))
  model.add(Conv2D(64,(3,3),padding='same'))
  model.add(BatchNormalization())
  model.add(Activation('relu'))
  model.add(MaxPooling2D(pool_size=(2,2)))


  model.add(ZeroPadding2D(padding=(1,1)))
  model.add(Conv2D(32,(3,3),padding='same'))
  model.add(BatchNormalization())
  model.add(Activation('relu'))


  model.add(ZeroPadding2D(padding=(1,1)))
  model.add(Conv2D(16,(3,3),padding='same'))
  model.add(BatchNormalization())
  model.add(Activation('relu'))
  model.add(MaxPooling2D(pool_size=(2,2)))

  model.add(Flatten())


  model.add(Dense(3072))
  model.add(BatchNormalization())
  model.add(Activation('relu'))
  model.add(Dropout(0.5))


  model.add(Dense(4096))
  model.add(BatchNormalization())
  model.add(Activation('relu'))
  model.add(Dropout(0.5))

  model.add(Dense(num_classes))
  model.add(BatchNormalization())
  model.add(Activation('softmax'))
  model.compile(Adam(lr=0.001),loss='categorical_crossentropy',metrics=['accuracy'])
  return model




In [0]:
model=create_model()
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_8 (Conv2D)            (None, 28, 28, 256)       31232     
_________________________________________________________________
batch_normalization_9 (Batch (None, 28, 28, 256)       1024      
_________________________________________________________________
activation_9 (Activation)    (None, 28, 28, 256)       0         
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 14, 14, 256)       0         
_________________________________________________________________
zero_padding2d_5 (ZeroPaddin (None, 18, 18, 256)       0         
_________________________________________________________________
conv2d_9 (Conv2D)            (None, 18, 18, 128)       819328    
_________________________________________________________________
batch_normalization_10 (Batc (None, 18, 18, 128)       512       
__________

history=model.fit(X_train, y_train, validation_split=0.1, epochs = 10, batch_size = 200, verbose = 1, shuffle = 1)

In [0]:
history=model.fit(X_train, y_train, validation_split=0.1, epochs = 10, batch_size = 200, verbose = 1, shuffle = 1)

Train on 54000 samples, validate on 6000 samples
Epoch 1/10
 1000/54000 [..............................] - ETA: 48:45 - loss: 1.6466 - acc: 0.4930

KeyboardInterrupt: ignored